{
	"version": 1738929590,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/platform-sheet0.png",
		"images/coin-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/oceanlayer-sheet0.png",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/buy.png",
		"images/sell.png",
		"images/bg.png",
		"media/boo.m4a",
		"media/boo.ogg",
		"media/yayyy.m4a",
		"media/yayyy.ogg",
		"media/coin collect.m4a",
		"media/coin collect.ogg",
		"media/wrong.m4a",
		"media/wrong.ogg",
		"media/bg.m4a",
		"media/bg.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}